const scrollbarData = [
  [
  {
    id:1,
    url_id:0,
    img:"src/Images/home.png",
    text:"Home",
    isHeld:false
  },
  {
    id:2,
    url_id:20,
    img:"src/Images/game_icon.png",
    text:"Games",
    isHeld:false
  },
  {
    id:3,
    url_id:2,
    img:"src/Images/automobiles.png",
    text:"Automobiles",
    isHeld:false
  },
  {
    id:4,
    url_id:17,
    img:"src/Images/sports.png",
    text:"Sports",
    isHeld:false
  },
  {
    id:5,
    url_id:24,
    img:"src/Images/entertainment.png",
    text:"Entertainment",
    isHeld:false
  },
  {
    id:6,
    url_id:28,
    img:"src/Images/tech.png",
    text:"Technologies",
    isHeld:false
  },
  {
    id:7,
    url_id:'10',
    img:"src/Images/music.png",
    text:"Music",
    isHeld:false
  },
  {
    id:8,
    url_id:22,
    img:"src/Images/blogs.png",
    text:"Blogs",
    isHeld:false
  },
  {
    id:9,
    url_id:25,
    img:"src/Images/news.png",
    text:"News",
    isHeld:false
  }
  ],
  [
    {
    id:10,
    img:"src/Images/cameron.png",
    text:"Cameron",
    isHeld:false
  },
  {
    id:11,
    img:"src/Images/gerard.png",
    text:"Gerard",
    isHeld:false
  },
  {
    id:12,
    img:"src/Images/jack.png",
    text:"Jack",
    isHeld:false
  },
  {
    id:13,
    img:"src/Images/megan.png",
    text:"Megan",
    isHeld:false
  },
  {
    id:14,
    img:"src/Images/simon.png",
    text:"Simon",
    isHeld:false
  }
  ]
]


export default scrollbarData;
